version: '2'
services:
  proxy:
    image: jwilder/nginx-proxy
    container_name: proxy
    privileged: true
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./docker-compose.d/certs:/etc/nginx/certs
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always
    # network_mode: shared
    # networks:
    #   app_net:
    #     ipv4_address: 172.16.238.2

  # web:
  #   image: nginx
  #   container_name: web
  #   privileged: true
  #   environment:
  #     VIRTUAL_HOST: cc5.me localhost
  #   restart: always
    # network_mode: shared
    # networks:
    #   app_net:
    #     ipv4_address: 172.16.238.3

networks:
  default:
    external:
      name: shared
  # app_net:
  #   driver: bridge
  #   ipam:
  #     driver: default
  #     config:
  #       - subnet: 172.16.238.0/24