version: '3'
services:
  proxy:
    image: jwilder/nginx-proxy
    container_name: proxy
    privileged: true
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./docker-compose.d/certs:/etc/nginx/certs:rw
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./server.conf:/etc/nginx/conf.d/server.conf
    restart: always

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    privileged: true
    ports:
      - "8025:8025"
      - "1025:1025"
    restart: always

networks:
  default:
    external: true
    name: shared
